version: '3.8'

services:
  zookeeper:
    image: debezium/zookeeper:3.0
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  kafka:
    container_name: kafka
    image: debezium/kafka:3.0
    ports:
      - "9092:9092"  # Expose Kafka on port 9092 for external access
      - "9093:9093"  # Expose Kafka on port 9093 for internal access
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://kafka:9093,OUTSIDE://localhost:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_LISTENERS=INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE  # Set the inter-broker listener
    depends_on:
      - zookeeper

  connect:
    image: debezium/connect:3.0
    ports:
      - 8083:8083
    environment:
      - BOOTSTRAP_SERVERS=kafka:9093
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses
    depends_on:
      - kafka
      - mysql

  mysql:
    container_name: mydb
    image: debezium/example-mysql:3.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mydb
      ADMINER_DESIGN: dracula
    ports:
      - 8181:8080
